name: Code Quality
on:
  push:
    branches:
      - 'main'
jobs:
  codequality:
    name: Code Quality
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 'v1.x'
      - name: test
        run: deno task test && deno task coverage
      - name: code coverage
        run: deno run -A https://deno.land/x/code_coverage/cli.ts --file coverage/coverage.lcov
      - name: lint
        run: deno lint
