name: 'On Push Pipeline'
on:
  workflow_dispatch:
  push:
    branches: ['**']
jobs:
  qualitygate:
    name: 'Quality Gate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.x'
      - name: test
        run: |
          deno task test && deno task coverage
          deno run -A https://deno.land/x/code_coverage/cli.ts --file coverage/coverage.lcov
      - name: lint
        run: deno lint
  tag:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    needs: ['qualitygate']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.x'
      - name: setup bumpup
        uses: danielr1996/gh-actions-bumpup@v9
      - run: cat version.json
      - name: bump
        run: bumpup bump
      - run: cat version.json
      - name: push
        run: | 
          git push
          git push --tags
      - name: build
        run: |
          cat version.json
          deno run -A ci/build.ts
          cat version.json
          deno run -A ci/copy.ts
          cat version.json
          deno run -A ci/copyversions.ts
      - name: publish
        run: deno run -A ci/publish.ts
        env:
          "B2_ACCESS_KEY": ${{secrets.B2_ACCESS_KEY}}
          "B2_SECRET_KEY": ${{secrets.B2_SECRET_KEY}}
          "B2_BUCKET_ID": ${{secrets.B2_BUCKET_ID}}
