name: 'On Push Pipeline'
on: [push]
jobs:
  qualitygate:
    name: 'Quality Gate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 'v1.x'
      - name: test
        run: |
          deno task test && deno task coverage
          deno run -A https://deno.land/x/code_coverage/cli.ts --file coverage/coverage.lcov
      - name: lint
        run: deno lint
#      - name: Trigger Tagging
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          event-type: pipeline/tag
  tag:
    name: 'Tag'
    runs-on: 'ubuntu-latest'
    needs: ['qualitygate']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: setup deno
#        uses: denolib/setup-deno@v2
#        with:
#          deno-version: 'v1.x'
      - name: setup bumpup
        uses: danielr1996/gh-actions-bumpup@main
        with:
          version: ''
      - name: tag
        run: bumpup bump
      - name: push
        run: |
          git push
          git push --tags
