name: 'On Push Pipeline'
on: [push]
jobs:
  qualitygate:
    name: 'Quality Gate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.x'
      - name: test
        run: |
          deno task test && deno task coverage
          deno run -A https://deno.land/x/code_coverage/cli.ts --file coverage/coverage.lcov
      - name: lint
        run: deno lint
  tag:
    name: 'Tag'
    runs-on: 'ubuntu-latest'
    needs: ['qualitygate']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup bumpup
        uses: danielr1996/gh-actions-bumpup@v9
      - name: tag
        run: bumpup bump
      - name: push
        run: |
          git push
          git push --tags
