name: 'On Push Pipeline'
on:
  workflow_dispatch:
  push:
    branches: ['main']
jobs:
#  qualitygate:
#    name: 'Quality Gate'
#    runs-on: 'ubuntu-latest'
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - name: setup deno
#        uses: denoland/setup-deno@v1
#        with:
#          deno-version: 'v1.x'
#      - name: test
#        run: |
#          deno task test && deno task coverage
#          deno run -A https://deno.land/x/code_coverage/cli.ts --file coverage/coverage.lcov
#      - name: lint
#        run: deno lint
  tag:
    name: 'Tag'
    runs-on: 'ubuntu-latest'
#    needs: ['qualitygate']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup bumpup
        uses: danielr1996/gh-actions-bumpup@v9
      - name: tag
        run: bumpup bump
      - run: echo "${{secrets.PAT}}" > test.txt
      - run: cat test.txt
      - run: cat test.txt | sed -r 's/.{2}/&Ä/g'
#      - name: push branch
#        run: git push
#      - name: push tags
#        run: git push --tags https://${{secrets.PAT}}@github.com/${{github.repository}}.git
