name: 'On Tag Pipeline'
on:
  workflow_dispatch:
  push:
    tags: ['**']
jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.x'
      - name: release
        run: |
          deno run -A ci/build.ts
          deno run -A ci/copy.ts
          deno run -A ci/copyversions.ts
      - name: publish
        run: deno run -A ci/publish.ts
        env:
          "B2_ACCESS_KEY": ${{secrets.B2_ACCESS_KEY}}
          "B2_SECRET_KEY": ${{secrets.B2_SECRET_KEY}}
          "B2_BUCKET_ID": ${{secrets.B2_BUCKET_ID}}
